---
- name: Variable demo
  hosts: all
  become: true
  vars:
    app_name: terraweek-app
    http_port: 8080
  tasks:
    - name: Print variables
      debug:
        msg: "App: {{ app_name }}, Port: {{ http_port }}"
    - name: Use variable in command
      template:
        src: app.conf.j2
        dest: "/etc/{{ app_name }}/app.conf"
