version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  notes-app:
    image: shubhamlondhe/notes-app:latest
    ports:
      - "8000:8000"
